[build]
builder = "NIXPACKS"
buildCommand = "npm install --prefix web-app/server && cd web-app/client-app && npm install && npm run build"

[deploy]
startCommand = "bash start.sh"
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
PORT = "3001"
